services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    depends_on:
#      - smart_city
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://10.177.29.226:13306/sctap
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - app-network

#  vue:
#    environment:
#      - NODE_ENV=production
#    build: ./frontend
#    depends_on:
#      - web
#      - node-red
#    ports:
#      - "8000:80"
#    networks:
#      - app-network
    #    environment:
    #      - VUE_APP_API_BASE_URL=http://localhost:8000 # 指定后端API的URL

#  node-red:
#    build: ./node-red
#    container_name: custom-node-red
#    ports:
#      - "1880:1880"
#    networks:
#      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge