version: '3'
services:
  springboot:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=host.docker.internal
    networks:
      - app-network

  vue:
    build: ./frontend
    ports:
      - "8082:8082"
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8080 # 指定后端API的URL
    networks:
      - app-network

  parent:
    build: ./sctapparent
    ports:
      - "8081:8081"
    networks:
      - app-network

  sdk:
    build: ./sdk-demo-v4-v2
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge