version: '3'
services:
  springboot:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=host.docker.internal
    networks:
      - app-network

  vue:
    build: ./frontend
    ports:
      - "8081:8081"
    environment:
      - VUE_APP_API_BASE_URL=http://springboot:8080 # 指定后端API的URL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge