services:
  smart_city_backend:
    container_name: smart-city-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  smart_city_frontend:
    container_name: smart-city-frontend
    environment:
      - NODE_ENV=production
      - VUE_APP_API_BASE_URL=http://localhost:8080
    build: ./frontend
    depends_on:
      - smart_city_backend
      - smart_city_node-red
    ports:
      - "8000:80"
    networks:
      - app-network

  smart_city_node-red:
    container_name: custom-node-red
    build: ./node-red
    ports:
      - "1880:1880"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge