services:
  springboot:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  vue:
    build: ./frontend
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge