version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: nanachi
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: