# Server port
server.port=8080
# Context path
server.servlet.context-path=/
# Datasource settings
spring.datasource.url=jdbc:mysql://10.176.65.202:3306/smart_city
spring.datasource.username=root
spring.datasource.password=123456a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Logging settings
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG
# SpringDoc OpenAPI
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
# spring mvc
spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.html
# spring servlet
spring.servlet.multipart.max-file-size=10MB
# Kafka
kafka.bootstrap.servers=10.176.65.202:9092
kafka.topic=sensor_value
kafka.topic.producer=env_update
# milvus
milvus.host=10.176.65.202
milvus.port=19530
# redis
spring.data.redis.host=10.176.65.202
spring.data.redis.port=6379
spring.data.redis.password=123456a
spring.data.redis.database=0
spring.data.redis.timeout=5000
# Neo4j
spring.neo4j.uri=bolt://10.176.65.202:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=123456ab
--add-opens java.base/java.lang=ALL-UNNAMED
# langchain4j qwen-plus
langchain4j.open-ai.chat-model.api-key=sk-22902121c1414dbb8c25cda74389c52c
langchain4j.open-ai.chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
langchain4j.open-ai.chat-model.model-name=qwen-max
langchain4j.open-ai.chat-model.temperature=0
# langchain4j gpt4o
#langchain4j.open-ai.chat-model.api-key=sk-SMltQxHCeYY8iATPrnJ5IbvQyF2JM2wslJerfvQJ4CObQ0jO
#langchain4j.open-ai.chat-model.base-url=https://api.bianxie.ai/v1
#langchain4j.open-ai.chat-model.model-name=gpt-4o
#langchain4j.open-ai.chat-model.temperature=0
# embedding model
spring.ai.dashscope.api-key=sk-22902121c1414dbb8c25cda74389c52c
# tsl
tsl.app.id=6bdece1382b5488a
tsl.app.code=Ubiquitous-OS
tsl.app.url=https://economy.smartyd.com/api/metrics/eventCenter/page
tsl.app.token=ZGIWMJHKMWZHZMVMNDAYYZLLMMU5YZE0MZU0YWFJYZFMNTYZNTDJODQ5ZJQ0OTG0
tsl.app.base-url=https://economy.smartyd.com/api
# event fusion
fusion.listen-network=848990d972bc4a7ab62321383e669bf3,25d1aa241a3340d5865df6d7fc4d2eea,03e651cb1599490a9b86086f1b78e5ec
fusion.ingestor.tsl-scheduled.enabled=false
# --- Deployment settings ---
# The deployment mode of the application, can be 'local' or 'distributed'
app.deploy-mode=distributed
# The role of the node in the distributed system, can be 'cloud' or 'edge'
app.node-role=cloud
# The URL of the cloud server (only needed if deploy-mode is 'distributed'); no trailing path, e.g. http://cloud-host:8080
app.cloud-url=